### ISSUE TITLE
Invalid key

### ISSUE THREAD

**Issue by nguyenj** [karma-runner/karma-browserstack-launcher#141]
I am providing the correct credentials and I'm sure of it since I'm able to use it to load up `https://api.browserstack.com/automate/browsers.json`; but recently I've been getting this error.

```
14 01 2019 15:13:29.019:INFO [launcher]: Starting browser chrome 71.0 (OS X High Sierra) on BrowserStack
Error: HTTP Basic: Access denied.

    at IncomingMessage.<anonymous> (~/project/node_modules/browserstack/lib/client.js:1:1)
    at emitNone (events.js:1:1)
    at IncomingMessage.emit (events.js:1:1)
    at endReadableNT (_stream_readable.js:1:1)
    at _combinedTickCallback (internal/process/next_tick.js:1:1)
    at process._tickCallback (internal/process/next_tick.js:1:1)

14 01 2019 15:13:30.968:ERROR [launcher.browserstack]: Can not establish the tunnel.
Error: child failed to start:
BrowserStackLocal v7.4

 *** Error: You provided an invalid key

To test an internal server, run:
./BrowserStackLocal --key <KEY>
Example:
./BrowserStackLocal --key DsVSdoJPBi2z44sbGFx1

To test HTML files, run:
./BrowserStackLocal --key <KEY> --folder <full path to local folder>
Example:
./BrowserStackLocal --key DsVSdoJPBi2z44sbGFx1 --folder /Applications/MAMP/htdocs/example/
```

**Comment by krish63** [comment]
The Error: **_**Error: You provided an invalid key**_** occurs when the provided Access Key does not exist. You can verify your access Key from [here.](https://www.browserstack.com/accounts/settings)

**Comment by nguyenj** [comment]
I found the issue, not sure why; but when copying the key it added a space at the end of the key.
