### ISSUE TITLE
TypeError: browser.on is not a function

### ISSUE THREAD

**Issue by gibson042** [karma-runner/karma-browserstack-launcher#47]
```sh
08 11 2015 14:18:56.615:ERROR [launcher]: [TypeError: browser.on is not a function]
TypeError: browser.on is not a function
    at /home/rgibson/Projects/sizzle/node_modules/karma/lib/launcher.js:94:17
    at next (/home/rgibson/Projects/sizzle/node_modules/karma/node_modules/batch/index.js:118:7)
    at Batch.end (/home/rgibson/Projects/sizzle/node_modules/karma/node_modules/batch/index.js:154:5)
    at launch (/home/rgibson/Projects/sizzle/node_modules/karma/lib/launcher.js:110:11)
    at invoke (/home/rgibson/Projects/sizzle/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/home/rgibson/Projects/sizzle/node_modules/karma/lib/server.js:170:24)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at doNTCallback1 (node.js:428:9)
    at process._tickCallback (node.js:350:17)
```

I think this should be getting `on` from [BaseLauncher](https://github.com/karma-runner/karma/blob/65080f535d34c02222c030974ff5acbe3287d0ab/lib/launchers/base.js#L22-L26) like [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher/blob/master/lib/sauce_launcher.js#L80-L91) (rather than a `self.on = emitter.on` kludge), but `baseLauncherDecorator` is not a drop-in change because this plugin provides a [`kill`](https://github.com/karma-runner/karma-browserstack-launcher/blob/f7d924e6c93942ac82265771e77fa82cd6585997/index.js#L209-L229) that is signature-incompatible with [BaseLauncher `kill` & `forceKill`](https://github.com/karma-runner/karma/blob/65080f535d34c02222c030974ff5acbe3287d0ab/lib/launchers/base.js#L44-L64).

**Comment by kof** [comment]
also getting this issue.
